name: bagnole_viewer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  rxdart: ^0.27.5
  injectable: ^1.5.3
  get_it: ^7.2.0
  provider: ^6.0.3
  path_provider: ^2.0.11
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_storage: ^10.3.4
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6
  flutter_image_compress: ^1.1.1
  file_picker: ^5.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.1.0
  flutter_animate: ^1.0.0
  hydrated_bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^1.5.3


  flutter_lints: ^2.0.0
  test: ^1.21.1

flutter:
  generate: true
  assets:
    - assets/drawable/
    - google_fonts/

  uses-material-design: true

